fix test fast_api

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -110,10 +110,17 @@ jobs:
           MLFLOW_TRACKING_USERNAME: rajeshxdatascience
           MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT }}
         run: |
-          uvicorn app:app --host 0.0.0.0 --port 5000 &
+          uvicorn app:app --host 0.0.0.0 --port 5000 > fastapi.log 2>&1 &
+          
           sleep 15
+          
+          curl --fail http://localhost:5000/ || (
+            echo "FastAPI failed to start"
+            cat fastapi.log
+            exit 1
+          )
 
-      - name: Run API tests
+      - name: Run FastAPI tests
         run: |
           pytest scripts/test_fast_api.py
             
